<?php
/**
 * OddsBookmakersMappingByFixtureIdResponseDataInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sportmonks
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Sportmonks\Model;

use \ArrayAccess;
use \Sportmonks\ObjectSerializer;

/**
 * OddsBookmakersMappingByFixtureIdResponseDataInner Class Doc Comment
 *
 * @category Class
 * @package  Sportmonks
 * @implements \ArrayAccess<string, mixed>
 */
class OddsBookmakersMappingByFixtureIdResponseDataInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OddsBookmakersMappingByFixtureIdResponse_data_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'fixture_id' => 'float',
        'bookmaker_id' => 'float',
        'bookmaker_name' => 'string',
        'bookmaker_event_id' => 'string',
        'bookmaker_event_url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'fixture_id' => null,
        'bookmaker_id' => null,
        'bookmaker_name' => null,
        'bookmaker_event_id' => null,
        'bookmaker_event_url' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'fixture_id' => false,
		'bookmaker_id' => false,
		'bookmaker_name' => false,
		'bookmaker_event_id' => false,
		'bookmaker_event_url' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fixture_id' => 'fixture_id',
        'bookmaker_id' => 'bookmaker_id',
        'bookmaker_name' => 'bookmaker_name',
        'bookmaker_event_id' => 'bookmaker_event_id',
        'bookmaker_event_url' => 'bookmaker_event_url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fixture_id' => 'setFixtureId',
        'bookmaker_id' => 'setBookmakerId',
        'bookmaker_name' => 'setBookmakerName',
        'bookmaker_event_id' => 'setBookmakerEventId',
        'bookmaker_event_url' => 'setBookmakerEventUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fixture_id' => 'getFixtureId',
        'bookmaker_id' => 'getBookmakerId',
        'bookmaker_name' => 'getBookmakerName',
        'bookmaker_event_id' => 'getBookmakerEventId',
        'bookmaker_event_url' => 'getBookmakerEventUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('fixture_id', $data ?? [], null);
        $this->setIfExists('bookmaker_id', $data ?? [], null);
        $this->setIfExists('bookmaker_name', $data ?? [], null);
        $this->setIfExists('bookmaker_event_id', $data ?? [], null);
        $this->setIfExists('bookmaker_event_url', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fixture_id
     *
     * @return float|null
     */
    public function getFixtureId()
    {
        return $this->container['fixture_id'];
    }

    /**
     * Sets fixture_id
     *
     * @param float|null $fixture_id fixture_id
     *
     * @return self
     */
    public function setFixtureId($fixture_id)
    {

        if (is_null($fixture_id)) {
            throw new \InvalidArgumentException('non-nullable fixture_id cannot be null');
        }

        $this->container['fixture_id'] = $fixture_id;

        return $this;
    }

    /**
     * Gets bookmaker_id
     *
     * @return float|null
     */
    public function getBookmakerId()
    {
        return $this->container['bookmaker_id'];
    }

    /**
     * Sets bookmaker_id
     *
     * @param float|null $bookmaker_id bookmaker_id
     *
     * @return self
     */
    public function setBookmakerId($bookmaker_id)
    {

        if (is_null($bookmaker_id)) {
            throw new \InvalidArgumentException('non-nullable bookmaker_id cannot be null');
        }

        $this->container['bookmaker_id'] = $bookmaker_id;

        return $this;
    }

    /**
     * Gets bookmaker_name
     *
     * @return string|null
     */
    public function getBookmakerName()
    {
        return $this->container['bookmaker_name'];
    }

    /**
     * Sets bookmaker_name
     *
     * @param string|null $bookmaker_name bookmaker_name
     *
     * @return self
     */
    public function setBookmakerName($bookmaker_name)
    {

        if (is_null($bookmaker_name)) {
            throw new \InvalidArgumentException('non-nullable bookmaker_name cannot be null');
        }

        $this->container['bookmaker_name'] = $bookmaker_name;

        return $this;
    }

    /**
     * Gets bookmaker_event_id
     *
     * @return string|null
     */
    public function getBookmakerEventId()
    {
        return $this->container['bookmaker_event_id'];
    }

    /**
     * Sets bookmaker_event_id
     *
     * @param string|null $bookmaker_event_id bookmaker_event_id
     *
     * @return self
     */
    public function setBookmakerEventId($bookmaker_event_id)
    {

        if (is_null($bookmaker_event_id)) {
            throw new \InvalidArgumentException('non-nullable bookmaker_event_id cannot be null');
        }

        $this->container['bookmaker_event_id'] = $bookmaker_event_id;

        return $this;
    }

    /**
     * Gets bookmaker_event_url
     *
     * @return string|null
     */
    public function getBookmakerEventUrl()
    {
        return $this->container['bookmaker_event_url'];
    }

    /**
     * Sets bookmaker_event_url
     *
     * @param string|null $bookmaker_event_url bookmaker_event_url
     *
     * @return self
     */
    public function setBookmakerEventUrl($bookmaker_event_url)
    {

        if (is_null($bookmaker_event_url)) {
            array_push($this->openAPINullablesSetToNull, 'bookmaker_event_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bookmaker_event_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['bookmaker_event_url'] = $bookmaker_event_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


