<?php
/**
 * SportSchedulesByTeamIdResponseDataInnerRoundsInnerFixturesInnerParticipantsInnerMetaTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sportmonks
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Sportmonks\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SportSchedulesByTeamIdResponseDataInnerRoundsInnerFixturesInnerParticipantsInnerMetaTest Class Doc Comment
 *
 * @category    Class
 * @description SportSchedulesByTeamIdResponseDataInnerRoundsInnerFixturesInnerParticipantsInnerMeta
 * @package     Sportmonks
 */
class SportSchedulesByTeamIdResponseDataInnerRoundsInnerFixturesInnerParticipantsInnerMetaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SportSchedulesByTeamIdResponseDataInnerRoundsInnerFixturesInnerParticipantsInnerMeta"
     */
    public function testSportSchedulesByTeamIdResponseDataInnerRoundsInnerFixturesInnerParticipantsInnerMeta()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
