<?php
/**
 * SportOddsPreMatchByFixtureAndMarketIdResponseSubscriptionInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sportmonks
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Sportmonks\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SportOddsPreMatchByFixtureAndMarketIdResponseSubscriptionInnerTest Class Doc Comment
 *
 * @category    Class
 * @description SportOddsPreMatchByFixtureAndMarketIdResponseSubscriptionInner
 * @package     Sportmonks
 */
class SportOddsPreMatchByFixtureAndMarketIdResponseSubscriptionInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SportOddsPreMatchByFixtureAndMarketIdResponseSubscriptionInner"
     */
    public function testSportOddsPreMatchByFixtureAndMarketIdResponseSubscriptionInner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta"
     */
    public function testPropertyMeta()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "plans"
     */
    public function testPropertyPlans()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "add_ons"
     */
    public function testPropertyAddOns()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "widgets"
     */
    public function testPropertyWidgets()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
