<?php
/**
 * SportPredictionsAllValueBetsResponseDataInnerPredictionsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sportmonks
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Sportmonks\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SportPredictionsAllValueBetsResponseDataInnerPredictionsTest Class Doc Comment
 *
 * @category    Class
 * @description SportPredictionsAllValueBetsResponseDataInnerPredictions
 * @package     Sportmonks
 */
class SportPredictionsAllValueBetsResponseDataInnerPredictionsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SportPredictionsAllValueBetsResponseDataInnerPredictions"
     */
    public function testSportPredictionsAllValueBetsResponseDataInnerPredictions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bet"
     */
    public function testPropertyBet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fair_odd"
     */
    public function testPropertyFairOdd()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "odd"
     */
    public function testPropertyOdd()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "stake"
     */
    public function testPropertyStake()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_value"
     */
    public function testPropertyIsValue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
