<?php
/**
 * SportStandingCorrectionsBySeasonIdResponseRateLimitTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sportmonks
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Sportmonks\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SportStandingCorrectionsBySeasonIdResponseRateLimitTest Class Doc Comment
 *
 * @category    Class
 * @description SportStandingCorrectionsBySeasonIdResponseRateLimit
 * @package     Sportmonks
 */
class SportStandingCorrectionsBySeasonIdResponseRateLimitTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SportStandingCorrectionsBySeasonIdResponseRateLimit"
     */
    public function testSportStandingCorrectionsBySeasonIdResponseRateLimit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "resets_in_seconds"
     */
    public function testPropertyResetsInSeconds()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "remaining"
     */
    public function testPropertyRemaining()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "requested_entity"
     */
    public function testPropertyRequestedEntity()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
