<?php
/**
 * OddsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Sportmonks
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Sportmonks\Test\Api;

use \Sportmonks\Configuration;
use \Sportmonks\ApiException;
use \Sportmonks\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class OddsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for bookmakerById
     *
     * By ID.
     *
     */
    public function testBookmakerById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for bookmakersAll
     *
     * All.
     *
     */
    public function testBookmakersAll()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for bookmakersByFixtureId
     *
     * By Fixture ID.
     *
     */
    public function testBookmakersByFixtureId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for bookmakersMappingByFixtureId
     *
     * Mapping by Fixture ID.
     *
     */
    public function testBookmakersMappingByFixtureId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for bookmakersSearch
     *
     * Search.
     *
     */
    public function testBookmakersSearch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fixturesUpcomingByMarketId
     *
     * Upcoming Fixtures by Market ID.
     *
     */
    public function testFixturesUpcomingByMarketId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for marketById
     *
     * By ID.
     *
     */
    public function testMarketById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for marketsAll
     *
     * All.
     *
     */
    public function testMarketsAll()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for marketsSearch
     *
     * Search.
     *
     */
    public function testMarketsSearch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
